version: '3.8'

services:
  gobalancer:
    image: gobalancer
    container_name: gobalancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    user: "root"
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-config", "/app/config.yaml"]
    depends_on:
      - backend1
      - backend2
    restart: unless-stopped

  backend1:
    image: nginx:alpine
    container_name: backend1
    labels:
      - "lb.enable=true"
    ports:
      - "8081:80"
    restart: unless-stopped

  backend2:
    image: nginx:alpine
    container_name: backend2
    labels:
      - "lb.enable=true"
    ports:
      - "8082:80"
    restart: unless-stopped