listen_address: ":8080"
use_iouring: true

algorithm: "least_connections"  #round_robin, least_connections, weighted, ip_hash

backends:
  - address: "10.0.0.4:3000"
    weight: 1
  - address: "10.0.0.5:3000"
    weight: 2

health_check:
  interval_sec: 5
  timeout_sec: 3
  retries: 2

timeout:
  client_idle_sec: 30
  backend_idle_sec: 30
  connect_timeout: 3

discovery:
  type: "docker" # Options: static, docker, kubernetes
  docker: {}
  # kubernetes:
  #   namespace: "default"
  #   service: "my-service"