listen_address: ":8080"
use_iouring: true

algorithm: "round_robin"  #round_robin, least_connections, weighted, ip_hash

backends:
  - address: "8082:80"
    weight: 1
  - address: "8081:80"
    weight: 2

health_check:
  interval_sec: 5
  timeout_sec: 3
  retries: 2

timeout:
  client_idle_sec: 30
  backend_idle_sec: 30
  connect_timeout: 3

discovery:
  type: "static" # Options: static, docker, kubernetes
  # docker: {}
  # kubernetes:
  #   namespace: "default"
  #   service: "my-service"