apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-config
data:
  config.yaml: |
    listen_address: ":8080"
    algorithm: "round_robin"
    use_iouring: false
    discovery:
      type: "kubernetes"
      kubernetes:
        namespace: "default"
        service: "my-target-service"
    health_check:
      interval_sec: 5
      timeout_sec: 2
      retries: 3
    timeout:
      client_idle_sec: 60
      backend_idle_sec: 60
      connect_timeout: 5
